// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lelomfelgftsnrkilsxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlbG9tZmVsZ2Z0c25ya2lsc3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjc3OTUsImV4cCI6MjA2NTY0Mzc5NX0.AJ8HJKa7C4yUeC5lh9oCdKkiaHmMW8Hdqw75sG6sNcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);